
version: '3.4'

services:
  database:
  image: "mcr.microsoft.com/mssql/server"
  environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  container_name: database

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/rentACar/WebAPI/Dockerfile